name: Build & Test (Pull Request)
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install bun
        run: npm install -g bun

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Test
        run: bun run --filter @superhero/api test:e2e
